name: agora_rtm
description: Flutter wrapper around the Agora Real Time Message SDKs for Android and iOS.
version: 2.2.6
homepage: https://www.agora.io
repository: https://github.com/AgoraIO-Extensions/Agora-Flutter-RTM-SDK.git
environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  ffi: ^2.1.4
  async: ^2.11.0
  meta: ^1.15.0
  iris_method_channel: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=1.0.0'
  build_runner: ^2.1.7
  json_serializable: ^6.1.1
  ffigen: ^19.0.0
flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agorartm.agora_rtm
        pluginClass: AgoraRtmPlugin
      ios:
        pluginClass: AgoraRtmPlugin
